// written by: Christina Segerholm
// tested by: Christina Segerholm
// debugged by: Christina Segerholm
package dataBaseC;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;

import configuration.Configure;

/**
 * Starts the DB C.
 * Chef will use this to continually update the inventory by giving it the name of the dish it started.
 * This will also update the chef when low inventory is met.
 * Waiter will use this when logging on to get the menu.
 * @author cms549
 *
 */
public class DatabaseCController {
	
	/**
	 * Name of file that holds the menu
	 * Each Line is a new item
	 * Format: TypeOfDish,NameOfDish,Price
	 * Exp: appetizer,Buffalo Wings,7.99
	 */
	private static final String menuFile = "src/configuration/menu.txt";
	
	/**
	 * Port number that Database C will be on.
	 */
	private final static int portNumber = Configure.getPortNumber("DatabaseCController");
	
	
	/**
	 * Inventory of restaurant. Maps Ingredient Name to Ingredient
	 */
	private static HashMap<String, Ingredient> inventory;
	
	/**
	 * Links name of dish to its dish data. 
	 * This will be used to figure out how much of an ingredient to decrement from the inventory for a started dish.
	 */
	private static HashMap<String, DishData> dishData;

	/**
	 * List of all the waiter senders that are connected to DB C.
	 * Links id of sender socket (generated by this class) to the sender
	 */
	public static HashMap<Integer,Sender> waiterSenders;
	
	/**
	 * Chef sender that is connected to DB C
	 */
	public static Sender chefSender;
	
	/**
	 * Holds the menu. Waiter will need this when logging on.
	 * See Menu.java
	 */
	public static Menu menu;
	
	
	/**
	 * Starts the Listener thread for each socket trying to connect with it.
	 * The listener will make the sender thread.
	 * Sockets should be from chefs or waiters.
	 * @param args
	 */
	public static void main(String[] args){
		menu = new Menu();
		waiterSenders= new HashMap<Integer,Sender>();
		//set up the inventory
		//set up dishdata converter
		loadMenuFromFile();
		if(args!=null && args.length==10){//for testing
			return;
		}
		try (ServerSocket serverSocket = new ServerSocket(portNumber)) { 
            while (true) {
               new Listener(serverSocket.accept()).start();
            }
        } catch (IOException e) {
            System.err.println("ERROR: DB C failed to start. Port " + portNumber+" is in use.");
            System.exit(-1);
        }
		
		
	}
	
	/**
	 * Adds a dish to the menu
	 * @param type - type of dish. (Appetizer, Dessert, Entree)
	 * @param dishname - name of the dish.
	 * @param price - price of the dish.
	 * @return 0 on success and -1 on failure/duplicate dish
	 */
	public static int addDishtoMenu(String type, String dishname, double price){
		Dish newdish = new Dish(dishname,price,type);
		if(menu.menu.containsKey(type)){
			HashMap<String,Dish> tem = menu.menu.get(type);
			if(tem.containsKey(dishname)){
				return -1;
			}else{
				tem.put(dishname, newdish);     //add new dish to the hashmap of the hashmap
                return 0;			
			}
		}else{//type does not exist
			HashMap<String,Dish> temp= new HashMap<String,Dish>();
			temp.put(dishname, newdish);
			menu.menu.put(type,temp);               // places the type in the hashmap
			return 0;
		}
	}
	
	/**
	 * Adds the ticket to the records
	 * @param tick - string representation of ticket from waiter interface
	 */
	public static void recordTicket(String tick){
		try (BufferedWriter br = new BufferedWriter(new FileWriter("TicketRecords.txt"))){
			String date = getDate();
			br.write(date+tick+"\n");
			
		} catch (Exception e) {
			e.printStackTrace();
		} 
	}
	
	/**
	 * Gets the date as a string
	 * @return mon/day/yr
	 */
	private static String getDate() {
		return Calendar.MONTH +"/"+Calendar.DAY_OF_MONTH +"/"+ Calendar.YEAR+" - ";
	}
	
	/**
	 * Decrements all ingredients in the dish and if low inventory happens will generate the proper notifications.
	 * @param dishName - name of dish you are dec ingredients for
	 */
	public static void decrementDish(String dishName){
		//find dish
		DishData d =dishData.get(dishName);
		Iterator<String> ingIT = d.listOfIngredients.keySet().iterator();
		//for each ingredient
		while(ingIT.hasNext()){
			String ingName = ingIT.next();
			Ingredient ing=inventory.get(ingName);
			ing.decrementAmountBy(d.amtOfIngredient.get(ingName));
			//Threshold met!!!!
			if(ing.checkThreshold()<=0){
				sendLowInventoryNotifications(ing);	
			}
			
			
		}
	}
	
	
	
	/**
	 * Load Menu From menu file
	 */
	public static void loadMenuFromFile(){
		
		try (BufferedReader br = new BufferedReader(new FileReader(menuFile))){

			String currLine;
			int i=0;
			while ((currLine = br.readLine()) != null) {
				if(i==0){//skip the header line
					i=1;
					continue;
				}
				String[] arr = currLine.split(",");
				addDishtoMenu(arr[0],arr[1], Double.parseDouble(arr[2]) );
			}
		} catch (Exception e) {
			e.printStackTrace();
		} 
		
	}

	/**
	 * Sends chef a low inventory notification also send waiter interfaces a message that will take off 
	 * the dishes with ingredient i in their menu.
	 * @param i - ingredient that is low
	 */
	public static void sendLowInventoryNotifications(Ingredient i ){
		//send chef a message
		if(chefSender!=null){
			chefSender.pendingMessages.offer("Low on Ingredient +"+i.name+".");
		}
		String dishes = "L";
		//go through each dishdata
		Iterator<String> it = dishData.keySet().iterator();
		while(it.hasNext()){
			DishData d = dishData.get(it.next());
			if(d.listOfIngredients.containsKey(i.name)){
				dishes = dishes+d.name+",";
			}
		}
		//make sure we added a dish to the list
		if(dishes.length()==1){
			return;
		}
		//send it to every server
		Iterator<Integer> itw = waiterSenders.keySet().iterator();
		while(itw.hasNext()){
			waiterSenders.get(itw.next()).pendingMessages.offer(dishes);
		}
		
	}


	/**
	 * Adds ingredient to inventory returns false if ingredient already exists
	 * @param ingredientName - name of ingredient to add to inventory
	 * @param amountLeft - amount of ingredient you have at the time
	 * @param unitOfAmount - unit that the amountLeft is measured in
	 * @param threshold- the amount at which you wish to be notified when inventory is low for this ingredient
	 * 	if you put it a threshold>=amount left or threshold = 0 then this will fail
	 * @return true on success, false on failure
	 */
	public static boolean addIngredientToInventory(String ingredientName,Double amountLeft, String unitOfAmount, Double threshold ){
		if(inventory.containsKey(ingredientName)){
			return false;
		}
		if(threshold>=amountLeft || threshold<0){
			return false;
		}
		inventory.put(ingredientName, new Ingredient(ingredientName, amountLeft, unitOfAmount, threshold));
		return true;
	}
	
	/**
	 * Getter for inventory
	 * @return inventory = HashMap<String, Ingredient> 
	 */
	public HashMap<String, Ingredient> getInventory(){
		return inventory;
	}
	
	/**
	 * Getter for dishdata
	 * @return dishData = HashMap<String, DishData> 
	 */
	public HashMap<String, DishData> getDishData(){
		return dishData;
	}
	/**
	 * Getter for menu file
	 * @return menuFile 
	 */
	public String getMenuFile(){
		return menuFile;
	}
	
	/**
	 * Getter for port number
	 * @return portNumber 
	 */
	public int getPortNumber(){
		return portNumber;
	}
	
}
